custom:
  service: ${file(./package.json):name}
  prefix: ${self:custom.service}-${env:ENVIRONMENT}-
  dotenv:
    file: file(./.env)
    basePath: ./

service: ${self:custom.service}

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${env:ENVIRONMENT}
  region: ${env:AWSC_REGION}
  timeout: 15
  environment:
    SERVICE: ${self:custom.service}
  lambdaHashingVersion: '20201221'

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - { Fn::GetAtt: ["${env:DB_PAYLOAD_DATA}", 'Arn'] }
            - { Fn::GetAtt: ["${env:DB_QRCODE_DATA}", 'Arn'] }

functions:
  retrieve_payload:
    handler: dist/handler.retrieve_payload
    events:
      - http:
          path: /retrieve-payload
          method: get
  send_payload:
    handler: dist/handler.send_payload
    events:
      - http:
          path: /send-payload
          method: post
  retrieve_qrcode:
    handler: dist/handler.retrieve_qrcode
    events:
      - http:
          path: /retrieve-qrcode
          method: get
  send_qrcode:
    handler: dist/handler.send_qrcode
    events:
      - http:
          path: /send-qrcode
          method: post

resources:
  Resources:
    payloaddata:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: ${env:DB_DEL_POLICY}
      Properties:
        TableName: ${self:custom.prefix}${env:DB_PAYLOAD_DATA}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    qrcodedata:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: ${env:DB_DEL_POLICY}
      Properties:
        TableName: ${self:custom.prefix}${env:DB_QRCODE_DATA}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-include-dependencies

