custom:
  service: ${file(./package.json):name}
  prefix: ${self:custom.service}-${env:ENVIRONMENT}-
  dotenv:
    file: file(./.env)
    basePath: ./

service: ${self:custom.service}

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${env:ENVIRONMENT}
  region: ${env:AWSC_REGION}
  timeout: 15
  environment:
    SERVICE: ${self:custom.service}
  lambdaHashingVersion: '20201221'

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { Fn::GetAtt: ["${env:DB_DATA}", 'Arn'] }

functions:
  hello:
    handler: dist/handler.retrieve_content
    events:
      - http:
          path: /retrieve-content
          method: get

resources:
  Resources:
    data:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: ${env:DB_DEL_POLICY}
      Properties:
        TableName: ${self:custom.prefix}${env:DB_DATA}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

plugins:
  - serverless-dotenv-plugin
